/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dae2ff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#0040a2",
        "tertiary-container": "#a33500",
        "surface-container-lowest": "#ffffff",
        "on-background": "#191b23",
        "surface-tint": "#0c56d0",
        "outline-variant": "#c3c6d6",
        "on-primary-fixed": "#001848",
        "primary": "#003d9b",
        "surface-container-highest": "#e1e2ec",
        "on-secondary-fixed-variant": "#783200",
        "background": "#faf8ff",
        "primary-container": "#0052cc",
        "secondary": "#9d4300",
        "secondary-container": "#fd761a",
        "on-surface": "#191b23",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#812800",
        "on-tertiary-fixed": "#380d00",
        "inverse-on-surface": "#f0f0fb",
        "secondary-fixed-dim": "#ffb690",
        "surface-bright": "#faf8ff",
        "inverse-surface": "#2e3038",
        "on-primary-container": "#c4d2ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e1e2ec",
        "tertiary": "#7b2600",
        "on-secondary-container": "#5c2400",
        "inverse-primary": "#b2c5ff",
        "error": "#ba1a1a",
        "outline": "#737685",
        "on-secondary-fixed": "#341100",
        "on-surface-variant": "#434654",
        "surface-container": "#ededf8",
        "primary-fixed-dim": "#b2c5ff",
        "surface-dim": "#d9d9e4",
        "secondary-fixed": "#ffdbca",
        "surface-container-high": "#e7e7f2",
        "tertiary-fixed-dim": "#ffb59b",
        "on-tertiary-container": "#ffc6b2",
        "on-secondary": "#ffffff",
        "surface": "#faf8ff",
        "tertiary-fixed": "#ffdbcf",
        "surface-container-low": "#f3f3fd",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Syne", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
